# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := mbed-os-pix


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += BSP_DISCO_F429ZI/Drivers/BSP/Components/ili9341/ili9341.o
OBJECTS += BSP_DISCO_F429ZI/Drivers/BSP/Components/l3gd20/l3gd20.o
OBJECTS += BSP_DISCO_F429ZI/Drivers/BSP/Components/stmpe811/stmpe811.o
OBJECTS += BSP_DISCO_F429ZI/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery.o
OBJECTS += BSP_DISCO_F429ZI/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_eeprom.o
OBJECTS += BSP_DISCO_F429ZI/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_gyroscope.o
OBJECTS += BSP_DISCO_F429ZI/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_io.o
OBJECTS += BSP_DISCO_F429ZI/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_lcd.o
OBJECTS += BSP_DISCO_F429ZI/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_sdram.o
OBJECTS += BSP_DISCO_F429ZI/Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_ts.o
OBJECTS += BSP_DISCO_F429ZI/Utilities/Fonts/font12.o
OBJECTS += BSP_DISCO_F429ZI/Utilities/Fonts/font16.o
OBJECTS += BSP_DISCO_F429ZI/Utilities/Fonts/font20.o
OBJECTS += BSP_DISCO_F429ZI/Utilities/Fonts/font24.o
OBJECTS += BSP_DISCO_F429ZI/Utilities/Fonts/font8.o
OBJECTS += LCD_DISCO_F429ZI/LCD_DISCO_F429ZI.o
OBJECTS += main.o
OBJECTS += mbed-os/drivers/AnalogIn.o
OBJECTS += mbed-os/drivers/BusIn.o
OBJECTS += mbed-os/drivers/BusInOut.o
OBJECTS += mbed-os/drivers/BusOut.o
OBJECTS += mbed-os/drivers/CAN.o
OBJECTS += mbed-os/drivers/Ethernet.o
OBJECTS += mbed-os/drivers/FlashIAP.o
OBJECTS += mbed-os/drivers/I2C.o
OBJECTS += mbed-os/drivers/I2CSlave.o
OBJECTS += mbed-os/drivers/InterruptIn.o
OBJECTS += mbed-os/drivers/InterruptManager.o
OBJECTS += mbed-os/drivers/RawSerial.o
OBJECTS += mbed-os/drivers/SPI.o
OBJECTS += mbed-os/drivers/SPISlave.o
OBJECTS += mbed-os/drivers/Serial.o
OBJECTS += mbed-os/drivers/SerialBase.o
OBJECTS += mbed-os/drivers/Ticker.o
OBJECTS += mbed-os/drivers/Timeout.o
OBJECTS += mbed-os/drivers/Timer.o
OBJECTS += mbed-os/drivers/TimerEvent.o
OBJECTS += mbed-os/drivers/UARTSerial.o
OBJECTS += mbed-os/events/EventQueue.o
OBJECTS += mbed-os/events/equeue/equeue.o
OBJECTS += mbed-os/events/equeue/equeue_mbed.o
OBJECTS += mbed-os/events/equeue/equeue_posix.o
OBJECTS += mbed-os/features/filesystem/Dir.o
OBJECTS += mbed-os/features/filesystem/File.o
OBJECTS += mbed-os/features/filesystem/FileSystem.o
OBJECTS += mbed-os/features/filesystem/bd/ChainingBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/HeapBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/MBRBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/SlicingBlockDevice.o
OBJECTS += mbed-os/features/filesystem/fat/ChaN/ccsbcs.o
OBJECTS += mbed-os/features/filesystem/fat/ChaN/ff.o
OBJECTS += mbed-os/features/filesystem/fat/FATFileSystem.o
OBJECTS += mbed-os/features/frameworks/greentea-client/source/greentea_metrics.o
OBJECTS += mbed-os/features/frameworks/greentea-client/source/greentea_serial.o
OBJECTS += mbed-os/features/frameworks/greentea-client/source/greentea_test_env.o
OBJECTS += mbed-os/features/frameworks/unity/source/unity.o
OBJECTS += mbed-os/features/frameworks/utest/mbed-utest-shim.o
OBJECTS += mbed-os/features/frameworks/utest/source/unity_handler.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_case.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_default_handlers.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_greentea_handlers.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_harness.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_shim.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_stack_trace.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_types.o
OBJECTS += mbed-os/features/mbedtls/platform/src/mbed_trng.o
OBJECTS += mbed-os/features/mbedtls/src/aes.o
OBJECTS += mbed-os/features/mbedtls/src/aesni.o
OBJECTS += mbed-os/features/mbedtls/src/arc4.o
OBJECTS += mbed-os/features/mbedtls/src/asn1parse.o
OBJECTS += mbed-os/features/mbedtls/src/asn1write.o
OBJECTS += mbed-os/features/mbedtls/src/base64.o
OBJECTS += mbed-os/features/mbedtls/src/bignum.o
OBJECTS += mbed-os/features/mbedtls/src/blowfish.o
OBJECTS += mbed-os/features/mbedtls/src/camellia.o
OBJECTS += mbed-os/features/mbedtls/src/ccm.o
OBJECTS += mbed-os/features/mbedtls/src/certs.o
OBJECTS += mbed-os/features/mbedtls/src/cipher.o
OBJECTS += mbed-os/features/mbedtls/src/cipher_wrap.o
OBJECTS += mbed-os/features/mbedtls/src/cmac.o
OBJECTS += mbed-os/features/mbedtls/src/ctr_drbg.o
OBJECTS += mbed-os/features/mbedtls/src/debug.o
OBJECTS += mbed-os/features/mbedtls/src/des.o
OBJECTS += mbed-os/features/mbedtls/src/dhm.o
OBJECTS += mbed-os/features/mbedtls/src/ecdh.o
OBJECTS += mbed-os/features/mbedtls/src/ecdsa.o
OBJECTS += mbed-os/features/mbedtls/src/ecjpake.o
OBJECTS += mbed-os/features/mbedtls/src/ecp.o
OBJECTS += mbed-os/features/mbedtls/src/ecp_curves.o
OBJECTS += mbed-os/features/mbedtls/src/entropy.o
OBJECTS += mbed-os/features/mbedtls/src/entropy_poll.o
OBJECTS += mbed-os/features/mbedtls/src/error.o
OBJECTS += mbed-os/features/mbedtls/src/gcm.o
OBJECTS += mbed-os/features/mbedtls/src/havege.o
OBJECTS += mbed-os/features/mbedtls/src/hmac_drbg.o
OBJECTS += mbed-os/features/mbedtls/src/md.o
OBJECTS += mbed-os/features/mbedtls/src/md2.o
OBJECTS += mbed-os/features/mbedtls/src/md4.o
OBJECTS += mbed-os/features/mbedtls/src/md5.o
OBJECTS += mbed-os/features/mbedtls/src/md_wrap.o
OBJECTS += mbed-os/features/mbedtls/src/memory_buffer_alloc.o
OBJECTS += mbed-os/features/mbedtls/src/net_sockets.o
OBJECTS += mbed-os/features/mbedtls/src/oid.o
OBJECTS += mbed-os/features/mbedtls/src/padlock.o
OBJECTS += mbed-os/features/mbedtls/src/pem.o
OBJECTS += mbed-os/features/mbedtls/src/pk.o
OBJECTS += mbed-os/features/mbedtls/src/pk_wrap.o
OBJECTS += mbed-os/features/mbedtls/src/pkcs11.o
OBJECTS += mbed-os/features/mbedtls/src/pkcs12.o
OBJECTS += mbed-os/features/mbedtls/src/pkcs5.o
OBJECTS += mbed-os/features/mbedtls/src/pkparse.o
OBJECTS += mbed-os/features/mbedtls/src/pkwrite.o
OBJECTS += mbed-os/features/mbedtls/src/platform.o
OBJECTS += mbed-os/features/mbedtls/src/ripemd160.o
OBJECTS += mbed-os/features/mbedtls/src/rsa.o
OBJECTS += mbed-os/features/mbedtls/src/sha1.o
OBJECTS += mbed-os/features/mbedtls/src/sha256.o
OBJECTS += mbed-os/features/mbedtls/src/sha512.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_cache.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_ciphersuites.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_cli.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_cookie.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_srv.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_ticket.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_tls.o
OBJECTS += mbed-os/features/mbedtls/src/threading.o
OBJECTS += mbed-os/features/mbedtls/src/timing.o
OBJECTS += mbed-os/features/mbedtls/src/version.o
OBJECTS += mbed-os/features/mbedtls/src/version_features.o
OBJECTS += mbed-os/features/mbedtls/src/x509.o
OBJECTS += mbed-os/features/mbedtls/src/x509_create.o
OBJECTS += mbed-os/features/mbedtls/src/x509_crl.o
OBJECTS += mbed-os/features/mbedtls/src/x509_crt.o
OBJECTS += mbed-os/features/mbedtls/src/x509_csr.o
OBJECTS += mbed-os/features/mbedtls/src/x509write_crt.o
OBJECTS += mbed-os/features/mbedtls/src/x509write_csr.o
OBJECTS += mbed-os/features/mbedtls/src/xtea.o
OBJECTS += mbed-os/features/mbedtls/targets/TARGET_STM/aes_alt.o
OBJECTS += mbed-os/features/netsocket/NetworkInterface.o
OBJECTS += mbed-os/features/netsocket/NetworkStack.o
OBJECTS += mbed-os/features/netsocket/Socket.o
OBJECTS += mbed-os/features/netsocket/SocketAddress.o
OBJECTS += mbed-os/features/netsocket/TCPServer.o
OBJECTS += mbed-os/features/netsocket/TCPSocket.o
OBJECTS += mbed-os/features/netsocket/UDPSocket.o
OBJECTS += mbed-os/features/netsocket/WiFiAccessPoint.o
OBJECTS += mbed-os/features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.o
OBJECTS += mbed-os/features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.o
OBJECTS += mbed-os/features/netsocket/cellular/generic_modem_driver/UARTCellularInterface.o
OBJECTS += mbed-os/features/netsocket/nsapi_dns.o
OBJECTS += mbed-os/hal/TARGET_FLASH_CMSIS_ALGO/flash_common_algo.o
OBJECTS += mbed-os/hal/mbed_gpio.o
OBJECTS += mbed-os/hal/mbed_lp_ticker_api.o
OBJECTS += mbed-os/hal/mbed_pinmap_common.o
OBJECTS += mbed-os/hal/mbed_ticker_api.o
OBJECTS += mbed-os/hal/mbed_us_ticker_api.o
OBJECTS += mbed-os/platform/ATCmdParser.o
OBJECTS += mbed-os/platform/CallChain.o
OBJECTS += mbed-os/platform/FileBase.o
OBJECTS += mbed-os/platform/FileHandle.o
OBJECTS += mbed-os/platform/FilePath.o
OBJECTS += mbed-os/platform/FileSystemHandle.o
OBJECTS += mbed-os/platform/LocalFileSystem.o
OBJECTS += mbed-os/platform/Stream.o
OBJECTS += mbed-os/platform/mbed_alloc_wrappers.o
OBJECTS += mbed-os/platform/mbed_application.o
OBJECTS += mbed-os/platform/mbed_assert.o
OBJECTS += mbed-os/platform/mbed_board.o
OBJECTS += mbed-os/platform/mbed_critical.o
OBJECTS += mbed-os/platform/mbed_error.o
OBJECTS += mbed-os/platform/mbed_interface.o
OBJECTS += mbed-os/platform/mbed_mem_trace.o
OBJECTS += mbed-os/platform/mbed_mktime.o
OBJECTS += mbed-os/platform/mbed_poll.o
OBJECTS += mbed-os/platform/mbed_retarget.o
OBJECTS += mbed-os/platform/mbed_rtc_time.o
OBJECTS += mbed-os/platform/mbed_sdk_boot.o
OBJECTS += mbed-os/platform/mbed_semihost_api.o
OBJECTS += mbed-os/platform/mbed_stats.o
OBJECTS += mbed-os/platform/mbed_wait_api_no_rtos.o
OBJECTS += mbed-os/platform/mbed_wait_api_rtos.o
OBJECTS += mbed-os/rtos/Mutex.o
OBJECTS += mbed-os/rtos/RtosTimer.o
OBJECTS += mbed-os/rtos/Semaphore.o
OBJECTS += mbed-os/rtos/Thread.o
OBJECTS += mbed-os/rtos/mbed_boot.o
OBJECTS += mbed-os/rtos/rtos_idle.o
OBJECTS += mbed-os/rtos/rtx4/cmsis_os1.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/RTX_Config.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/TARGET_RTOS_M4_M7/TOOLCHAIN_GCC/irq_cm4f.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rt_OsEventObserver.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_delay.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_evflags.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_evr.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_kernel.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_lib.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_memory.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_mempool.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_msgqueue.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_mutex.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_semaphore.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_system.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_thread.o
OBJECTS += mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_timer.o
OBJECTS += mbed-os/rtos/rtx5/mbed_rtx_handlers.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_DISCO_F429ZI/PeripheralPins.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_DISCO_F429ZI/system_stm32f4xx.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_GCC_ARM/startup_stm32f429xx.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/flash_api.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/system_init_pre.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/analogin_api.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/analogout_api.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/hal_init_pre.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_can.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cec.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cortex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_crc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dfsdm.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma2d.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dsi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_eth.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ramfunc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_gpio.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hcd.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_irda.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_iwdg.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_lptim.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_mmc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_msp_template.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nand.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nor.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pccard.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_qspi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rng.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sd.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sdram.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_smartcard.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spdifrx.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sram.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_uart.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_usart.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_wwdg.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_adc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_crc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dac.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma2d.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_exti.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fmc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fsmc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_gpio.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_i2c.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_lptim.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_pwr.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rcc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rng.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rtc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_sdmmc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_spi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_tim.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usart.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usb.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_utils.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/gpio_irq_device.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/mbed_overrides.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/pwmout_device.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/serial_device.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32F4/spi_api.o
OBJECTS += mbed-os/targets/TARGET_STM/can_api.o
OBJECTS += mbed-os/targets/TARGET_STM/gpio_api.o
OBJECTS += mbed-os/targets/TARGET_STM/gpio_irq_api.o
OBJECTS += mbed-os/targets/TARGET_STM/hal_tick_16b.o
OBJECTS += mbed-os/targets/TARGET_STM/hal_tick_32b.o
OBJECTS += mbed-os/targets/TARGET_STM/i2c_api.o
OBJECTS += mbed-os/targets/TARGET_STM/lp_ticker.o
OBJECTS += mbed-os/targets/TARGET_STM/pinmap.o
OBJECTS += mbed-os/targets/TARGET_STM/port_api.o
OBJECTS += mbed-os/targets/TARGET_STM/pwmout_api.o
OBJECTS += mbed-os/targets/TARGET_STM/rtc_api.o
OBJECTS += mbed-os/targets/TARGET_STM/serial_api.o
OBJECTS += mbed-os/targets/TARGET_STM/sleep.o
OBJECTS += mbed-os/targets/TARGET_STM/stm_spi_api.o
OBJECTS += mbed-os/targets/TARGET_STM/trng_api.o
OBJECTS += mbed-os/targets/TARGET_STM/us_ticker_16b.o
OBJECTS += mbed-os/targets/TARGET_STM/us_ticker_32b.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_abs_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_abs_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_abs_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_abs_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_add_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_add_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_add_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_add_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_dot_prod_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_dot_prod_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_dot_prod_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_dot_prod_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_mult_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_mult_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_mult_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_mult_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_negate_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_negate_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_negate_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_negate_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_offset_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_offset_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_offset_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_offset_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_scale_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_scale_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_scale_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_scale_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_shift_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_shift_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_shift_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_sub_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_sub_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_sub_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/BasicMathFunctions/arm_sub_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/CommonTables/arm_common_tables.o
OBJECTS += mbed-dsp/cmsis_dsp/CommonTables/arm_const_structs.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_conj_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_conj_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_conj_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_dot_prod_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_dot_prod_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_dot_prod_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_mag_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_mag_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_mag_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_mag_squared_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_mag_squared_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_mag_squared_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_mult_cmplx_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_mult_cmplx_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_mult_cmplx_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_mult_real_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_mult_real_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/ComplexMathFunctions/arm_cmplx_mult_real_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/ControllerFunctions/arm_pid_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/ControllerFunctions/arm_pid_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/ControllerFunctions/arm_pid_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/ControllerFunctions/arm_pid_reset_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/ControllerFunctions/arm_pid_reset_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/ControllerFunctions/arm_pid_reset_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/ControllerFunctions/arm_sin_cos_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/ControllerFunctions/arm_sin_cos_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FastMathFunctions/arm_cos_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FastMathFunctions/arm_cos_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FastMathFunctions/arm_cos_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FastMathFunctions/arm_sin_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FastMathFunctions/arm_sin_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FastMathFunctions/arm_sin_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FastMathFunctions/arm_sqrt_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FastMathFunctions/arm_sqrt_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df1_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df1_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df1_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df2T_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df2T_f64.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_fast_opt_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_fast_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_fast_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_opt_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_opt_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_partial_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_partial_fast_opt_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_partial_fast_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_partial_fast_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_partial_opt_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_partial_opt_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_partial_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_partial_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_partial_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_conv_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_correlate_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_correlate_fast_opt_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_correlate_fast_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_correlate_fast_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_correlate_opt_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_correlate_opt_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_correlate_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_correlate_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_correlate_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_decimate_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_decimate_fast_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_decimate_fast_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_decimate_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_decimate_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_decimate_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_decimate_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_decimate_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_fast_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_fast_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_init_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_interpolate_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_interpolate_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_interpolate_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_interpolate_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_interpolate_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_interpolate_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_lattice_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_lattice_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_lattice_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_lattice_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_lattice_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_lattice_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_sparse_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_sparse_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_sparse_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_sparse_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_sparse_init_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_sparse_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_sparse_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_fir_sparse_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_iir_lattice_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_iir_lattice_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_iir_lattice_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_iir_lattice_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_iir_lattice_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_iir_lattice_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_lms_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_lms_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_lms_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_lms_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_lms_norm_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_lms_norm_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_lms_norm_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_lms_norm_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_lms_norm_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_lms_norm_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_lms_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/FilteringFunctions/arm_lms_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_add_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_add_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_add_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_cmplx_mult_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_cmplx_mult_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_cmplx_mult_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_inverse_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_inverse_f64.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_mult_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_mult_fast_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_mult_fast_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_mult_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_mult_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_scale_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_scale_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_scale_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_sub_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_sub_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_sub_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_trans_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_trans_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/MatrixFunctions/arm_mat_trans_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_max_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_max_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_max_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_max_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_mean_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_mean_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_mean_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_mean_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_min_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_min_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_min_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_min_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_power_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_power_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_power_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_power_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_rms_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_rms_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_rms_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_std_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_std_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_std_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_var_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_var_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/StatisticsFunctions/arm_var_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_copy_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_copy_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_copy_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_copy_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_fill_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_fill_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_fill_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_fill_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_float_to_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_float_to_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_float_to_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_q15_to_float.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_q15_to_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_q15_to_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_q31_to_float.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_q31_to_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_q31_to_q7.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_q7_to_float.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_q7_to_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/arm_q7_to_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/SupportFunctions/math_helper.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_bitreversal.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_bitreversal2.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_radix2_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_radix2_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_radix2_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_radix2_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_radix2_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_radix2_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_radix4_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_radix4_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_radix4_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_radix4_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_radix4_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_radix4_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_cfft_radix8_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_dct4_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_dct4_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_dct4_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_dct4_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_dct4_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_dct4_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_rfft_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_rfft_fast_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_rfft_fast_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_rfft_init_f32.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_rfft_init_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_rfft_init_q31.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_rfft_q15.o
OBJECTS += mbed-dsp/cmsis_dsp/TransformFunctions/arm_rfft_q31.o
OBJECTS += mbed-dsp/dsp/Sine_f32.o


INCLUDE_PATHS += -I../
INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I../BSP_DISCO_F429ZI
INCLUDE_PATHS += -I../BSP_DISCO_F429ZI/Drivers
INCLUDE_PATHS += -I../BSP_DISCO_F429ZI/Drivers/BSP
INCLUDE_PATHS += -I../BSP_DISCO_F429ZI/Drivers/BSP/Components
INCLUDE_PATHS += -I../BSP_DISCO_F429ZI/Drivers/BSP/Components/Common
INCLUDE_PATHS += -I../BSP_DISCO_F429ZI/Drivers/BSP/Components/ili9341
INCLUDE_PATHS += -I../BSP_DISCO_F429ZI/Drivers/BSP/Components/l3gd20
INCLUDE_PATHS += -I../BSP_DISCO_F429ZI/Drivers/BSP/Components/stmpe811
INCLUDE_PATHS += -I../BSP_DISCO_F429ZI/Drivers/BSP/STM32F429I-Discovery
INCLUDE_PATHS += -I../BSP_DISCO_F429ZI/Utilities
INCLUDE_PATHS += -I../BSP_DISCO_F429ZI/Utilities/Fonts
INCLUDE_PATHS += -I../LCD_DISCO_F429ZI
INCLUDE_PATHS += -I../fft_lib
INCLUDE_PATHS += -I../img
INCLUDE_PATHS += -I../mbed-os/.
INCLUDE_PATHS += -I../mbed-os/cmsis
INCLUDE_PATHS += -I../mbed-os/cmsis/TARGET_CORTEX_M
INCLUDE_PATHS += -I../mbed-os/cmsis/TARGET_CORTEX_M/TOOLCHAIN_GCC
INCLUDE_PATHS += -I../mbed-os/drivers
INCLUDE_PATHS += -I../mbed-os/events
INCLUDE_PATHS += -I../mbed-os/events/equeue
INCLUDE_PATHS += -I../mbed-os/features
INCLUDE_PATHS += -I../mbed-os/features/filesystem
INCLUDE_PATHS += -I../mbed-os/features/filesystem/bd
INCLUDE_PATHS += -I../mbed-os/features/filesystem/fat
INCLUDE_PATHS += -I../mbed-os/features/filesystem/fat/ChaN
INCLUDE_PATHS += -I../mbed-os/features/frameworks
INCLUDE_PATHS += -I../mbed-os/features/frameworks/greentea-client
INCLUDE_PATHS += -I../mbed-os/features/frameworks/greentea-client/greentea-client
INCLUDE_PATHS += -I../mbed-os/features/frameworks/greentea-client/source
INCLUDE_PATHS += -I../mbed-os/features/frameworks/unity
INCLUDE_PATHS += -I../mbed-os/features/frameworks/unity/source
INCLUDE_PATHS += -I../mbed-os/features/frameworks/unity/unity
INCLUDE_PATHS += -I../mbed-os/features/frameworks/utest
INCLUDE_PATHS += -I../mbed-os/features/frameworks/utest/source
INCLUDE_PATHS += -I../mbed-os/features/frameworks/utest/utest
INCLUDE_PATHS += -I../mbed-os/features/mbedtls
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/importer
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/inc
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/inc/mbedtls
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/platform
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/platform/inc
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/platform/src
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/src
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/targets
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/targets/TARGET_STM
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/targets/TARGET_STM/TARGET_STM32F4
INCLUDE_PATHS += -I../mbed-os/features/nanostack
INCLUDE_PATHS += -I../mbed-os/features/netsocket
INCLUDE_PATHS += -I../mbed-os/features/netsocket/cellular
INCLUDE_PATHS += -I../mbed-os/features/netsocket/cellular/generic_modem_driver
INCLUDE_PATHS += -I../mbed-os/features/netsocket/cellular/utils
INCLUDE_PATHS += -I../mbed-os/features/storage
INCLUDE_PATHS += -I../mbed-os/hal
INCLUDE_PATHS += -I../mbed-os/hal/TARGET_FLASH_CMSIS_ALGO
INCLUDE_PATHS += -I../mbed-os/hal/storage_abstraction
INCLUDE_PATHS += -I../mbed-os/platform
INCLUDE_PATHS += -I../mbed-os/rtos
INCLUDE_PATHS += -I../mbed-os/rtos/rtx4
INCLUDE_PATHS += -I../mbed-os/rtos/rtx5
INCLUDE_PATHS += -I../mbed-os/rtos/rtx5/TARGET_CORTEX_M
INCLUDE_PATHS += -I../mbed-os/rtos/rtx5/TARGET_CORTEX_M/TARGET_RTOS_M4_M7
INCLUDE_PATHS += -I../mbed-os/rtos/rtx5/TARGET_CORTEX_M/TARGET_RTOS_M4_M7/TOOLCHAIN_GCC
INCLUDE_PATHS += -I../mbed-os/targets
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_DISCO_F429ZI
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_GCC_ARM
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device
INCLUDE_PATHS += -I../mbed-dsp
INCLUDE_PATHS += -I../mbed-dsp/cmsis_dsp
INCLUDE_PATHS += -I../mbed-dsp/cmsis_dsp/BasicMathFunctions
INCLUDE_PATHS += -I../mbed-dsp/cmsis_dsp/CommonTables
INCLUDE_PATHS += -I../mbed-dsp/cmsis_dsp/ComplexMathFunctions
INCLUDE_PATHS += -I../mbed-dsp/cmsis_dsp/ControllerFunctions
INCLUDE_PATHS += -I../mbed-dsp/cmsis_dsp/FastMathFunctions
INCLUDE_PATHS += -I../mbed-dsp/cmsis_dsp/FilteringFunctions
INCLUDE_PATHS += -I../mbed-dsp/cmsis_dsp/MatrixFunctions
INCLUDE_PATHS += -I../mbed-dsp/cmsis_dsp/StatisticsFunctions
INCLUDE_PATHS += -I../mbed-dsp/cmsis_dsp/SupportFunctions
INCLUDE_PATHS += -I../mbed-dsp/cmsis_dsp/TransformFunctions
INCLUDE_PATHS += -I../mbed-dsp/dsp


LIBRARY_PATHS :=
LIBRARIES :=
LINKER_SCRIPT ?= ../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_GCC_ARM/STM32F429xI.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = '/opt/gcc4mbed/gcc-arm-none-eabi/bin/arm-none-eabi-gcc' '-x' 'assembler-with-cpp' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-g1' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
CC      = '/opt/gcc4mbed/gcc-arm-none-eabi/bin/arm-none-eabi-gcc' '-std=gnu99' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-g1' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
CPP     = '/opt/gcc4mbed/gcc-arm-none-eabi/bin/arm-none-eabi-g++' '-std=gnu++98' '-fno-rtti' '-Wvla' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-g1' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
LD      = '/opt/gcc4mbed/gcc-arm-none-eabi/bin/arm-none-eabi-gcc'
ELF2BIN = '/opt/gcc4mbed/gcc-arm-none-eabi/bin/arm-none-eabi-objcopy'
PREPROC = '/opt/gcc4mbed/gcc-arm-none-eabi/bin/arm-none-eabi-cpp' '-E' '-P' '-Wl,--gc-sections' '-Wl,--wrap,main' '-Wl,--wrap,_malloc_r' '-Wl,--wrap,_free_r' '-Wl,--wrap,_realloc_r' '-Wl,--wrap,_memalign_r' '-Wl,--wrap,_calloc_r' '-Wl,--wrap,exit' '-Wl,--wrap,atexit' '-Wl,-n' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'


C_FLAGS += -std=gnu99
C_FLAGS += -DTARGET_STM32F429xx
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -D__MBED__=1
C_FLAGS += -DDEVICE_I2CSLAVE=1
C_FLAGS += -D__FPU_PRESENT=1
C_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
C_FLAGS += -DUSBHOST_OTHER
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -DTARGET_RTOS_M4_M7
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1525197610.3
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DTOOLCHAIN_object
C_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
C_FLAGS += -DTARGET_STM32F4
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DTARGET_FLASH_CMSIS_ALGO
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DDEVICE_CAN=1
C_FLAGS += -DARM_MATH_CM4
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DTARGET_LIKE_CORTEX_M4
C_FLAGS += -DDEVICE_ANALOGOUT=1
C_FLAGS += -DTARGET_M4
C_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DTARGET_CORTEX
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DTARGET_STM32F429
C_FLAGS += -DRTC_LSI=1
C_FLAGS += -D__CORTEX_M4
C_FLAGS += -DDEVICE_STDIO_MESSAGES=1
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -DTARGET_DISCO_F429ZI
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DTARGET_RELEASE
C_FLAGS += -DTARGET_STM
C_FLAGS += -DDEVICE_SERIAL_FC=1
C_FLAGS += -DDEVICE_TRNG=1
C_FLAGS += -DTARGET_STM32F429ZI
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DDEVICE_ERROR_RED=1
C_FLAGS += -DTARGET_STM32F429xI
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DDEVICE_FLASH=1
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -include
C_FLAGS += mbed_config.h

CXX_FLAGS += -std=gnu++98
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -DTARGET_STM32F429xx
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DDEVICE_I2CSLAVE=1
CXX_FLAGS += -D__FPU_PRESENT=1
CXX_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
CXX_FLAGS += -DUSBHOST_OTHER
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -DTARGET_RTOS_M4_M7
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1525197610.3
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DTOOLCHAIN_object
CXX_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
CXX_FLAGS += -DTARGET_STM32F4
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DTARGET_FLASH_CMSIS_ALGO
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DDEVICE_CAN=1
CXX_FLAGS += -DARM_MATH_CM4
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M4
CXX_FLAGS += -DDEVICE_ANALOGOUT=1
CXX_FLAGS += -DTARGET_M4
CXX_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DTARGET_CORTEX
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DTARGET_STM32F429
CXX_FLAGS += -DRTC_LSI=1
CXX_FLAGS += -D__CORTEX_M4
CXX_FLAGS += -DDEVICE_STDIO_MESSAGES=1
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -DTARGET_DISCO_F429ZI
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DTARGET_RELEASE
CXX_FLAGS += -DTARGET_STM
CXX_FLAGS += -DDEVICE_SERIAL_FC=1
CXX_FLAGS += -DDEVICE_TRNG=1
CXX_FLAGS += -DTARGET_STM32F429ZI
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DDEVICE_ERROR_RED=1
CXX_FLAGS += -DTARGET_STM32F429xI
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DDEVICE_FLASH=1
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
ASM_FLAGS += -DRTC_LSI=1
ASM_FLAGS += -D__CORTEX_M4
ASM_FLAGS += -DARM_MATH_CM4
ASM_FLAGS += -D__FPU_PRESENT=1
ASM_FLAGS += -DUSBHOST_OTHER
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -I../.
ASM_FLAGS += -I../img
ASM_FLAGS += -I../LCD_DISCO_F429ZI
ASM_FLAGS += -I../BSP_DISCO_F429ZI
ASM_FLAGS += -I../BSP_DISCO_F429ZI/Drivers
ASM_FLAGS += -I../BSP_DISCO_F429ZI/Drivers/BSP
ASM_FLAGS += -I../BSP_DISCO_F429ZI/Drivers/BSP/Components
ASM_FLAGS += -I../BSP_DISCO_F429ZI/Drivers/BSP/Components/Common
ASM_FLAGS += -I../BSP_DISCO_F429ZI/Drivers/BSP/Components/ili9341
ASM_FLAGS += -I../BSP_DISCO_F429ZI/Drivers/BSP/Components/l3gd20
ASM_FLAGS += -I../BSP_DISCO_F429ZI/Drivers/BSP/Components/stmpe811
ASM_FLAGS += -I../BSP_DISCO_F429ZI/Drivers/BSP/STM32F429I-Discovery
ASM_FLAGS += -I../BSP_DISCO_F429ZI/Utilities
ASM_FLAGS += -I../BSP_DISCO_F429ZI/Utilities/Fonts
ASM_FLAGS += -I../mbed-os/.
ASM_FLAGS += -I../mbed-os/features
ASM_FLAGS += -I../mbed-os/features/frameworks
ASM_FLAGS += -I../mbed-os/features/frameworks/greentea-client
ASM_FLAGS += -I../mbed-os/features/frameworks/greentea-client/greentea-client
ASM_FLAGS += -I../mbed-os/features/frameworks/greentea-client/source
ASM_FLAGS += -I../mbed-os/features/frameworks/unity
ASM_FLAGS += -I../mbed-os/features/frameworks/unity/source
ASM_FLAGS += -I../mbed-os/features/frameworks/unity/unity
ASM_FLAGS += -I../mbed-os/features/frameworks/utest
ASM_FLAGS += -I../mbed-os/features/frameworks/utest/source
ASM_FLAGS += -I../mbed-os/features/frameworks/utest/utest
ASM_FLAGS += -I../mbed-os/features/mbedtls
ASM_FLAGS += -I../mbed-os/features/mbedtls/importer
ASM_FLAGS += -I../mbed-os/features/mbedtls/inc
ASM_FLAGS += -I../mbed-os/features/mbedtls/inc/mbedtls
ASM_FLAGS += -I../mbed-os/features/mbedtls/src
ASM_FLAGS += -I../mbed-os/features/mbedtls/platform
ASM_FLAGS += -I../mbed-os/features/mbedtls/platform/inc
ASM_FLAGS += -I../mbed-os/features/mbedtls/platform/src
ASM_FLAGS += -I../mbed-os/features/mbedtls/targets
ASM_FLAGS += -I../mbed-os/features/mbedtls/targets/TARGET_STM
ASM_FLAGS += -I../mbed-os/features/mbedtls/targets/TARGET_STM/TARGET_STM32F4
ASM_FLAGS += -I../mbed-os/features/nanostack
ASM_FLAGS += -I../mbed-os/features/storage
ASM_FLAGS += -I../mbed-os/features/netsocket
ASM_FLAGS += -I../mbed-os/features/netsocket/cellular
ASM_FLAGS += -I../mbed-os/features/netsocket/cellular/generic_modem_driver
ASM_FLAGS += -I../mbed-os/features/netsocket/cellular/utils
ASM_FLAGS += -I../mbed-os/features/filesystem
ASM_FLAGS += -I../mbed-os/features/filesystem/bd
ASM_FLAGS += -I../mbed-os/features/filesystem/fat
ASM_FLAGS += -I../mbed-os/features/filesystem/fat/ChaN
ASM_FLAGS += -I../mbed-os/cmsis
ASM_FLAGS += -I../mbed-os/cmsis/TARGET_CORTEX_M
ASM_FLAGS += -I../mbed-os/cmsis/TARGET_CORTEX_M/TOOLCHAIN_GCC
ASM_FLAGS += -I../mbed-os/drivers
ASM_FLAGS += -I../mbed-os/events
ASM_FLAGS += -I../mbed-os/events/equeue
ASM_FLAGS += -I../mbed-os/rtos
ASM_FLAGS += -I../mbed-os/rtos/rtx4
ASM_FLAGS += -I../mbed-os/rtos/rtx5
ASM_FLAGS += -I../mbed-os/rtos/rtx5/TARGET_CORTEX_M
ASM_FLAGS += -I../mbed-os/rtos/rtx5/TARGET_CORTEX_M/TARGET_RTOS_M4_M7
ASM_FLAGS += -I../mbed-os/rtos/rtx5/TARGET_CORTEX_M/TARGET_RTOS_M4_M7/TOOLCHAIN_GCC
ASM_FLAGS += -I../mbed-os/hal
ASM_FLAGS += -I../mbed-os/hal/storage_abstraction
ASM_FLAGS += -I../mbed-os/hal/TARGET_FLASH_CMSIS_ALGO
ASM_FLAGS += -I../mbed-os/platform
ASM_FLAGS += -I../mbed-os/targets
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_DISCO_F429ZI
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_GCC_ARM
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device


LD_FLAGS :=-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys  -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size


all: $(PROJECT).bin $(PROJECT).hex size


.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  


.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
	@$(PREPROC) $< -o $@



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter-out %.o, $^) $(LIBRARY_PATHS) --output $@ $(filter %.o, $^) $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@
	+@echo "===== bin file ready to flash: $(OBJDIR)/$@ =====" 

$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
